#ifndef STAGE_3_H
#define STAGE_3_H

#include <string>
#include "dialog.h"

/*
    This file represents the fourth stage of the game.
    It contains the dialog nodes for the fourth stage.

    Each dialog node is represented by a Dialog struct.
    The pointer to the next dialog node is stored in the next field.
*/

inline extern Dialog dialog_3_21 = create_stage_end("As the conversation between Conan and Vincent came to a close, the room fell into an uneasy stillness. Shadows enveloped the space, concealing the secrets that lingered in the air. Conan's sharp gaze pierced through the smoke-filled atmosphere, his mind a labyrinth of deduction and speculation. Though Vincent's words danced upon the edge of truth and deception, Conan remained vigilant, his senses honed to the subtlest of cues. As he bid Vincent farewell, a heavy silence whispered promises of a relentless pursuit for justice. The night was far from over, and the winding path of the investigation grew ever more treacherous. In the depths of his thoughts, Conan knew that hidden beneath the veil of innocence, the darkest truths lay waiting to be uncovered. With a steely resolve, he stepped into the night, ready to chase the shadows until the final piece of the puzzle fell into place.", 1, 3);
inline extern Dialog dialog_3_20 = create_npc_dialog("Odd indeed, detective. Thomas is usually quite reliable in his duties. The fact that he lost sight of Marcus raises questions. One would think he'd have a keen eye on the suspects, especially with so much at stake. But who am I to judge? Just an observer in this twisted game of shadows.", 0, 3, &dialog_3_21);
inline extern Dialog dialog_3_19 = create_npc_dialog("And what about Thomas Reynolds losing track of Marcus during his surveillance? Does that strike you as odd as well?", 0, 3, &dialog_3_20);
inline extern Dialog dialog_3_18 = create_npc_dialog("Marcus, oh Marcus. He's been acting quite peculiar lately. I couldn't help but notice his nosy behavior, poking around where he shouldn't be. It raised my suspicions, I must say. I find it rather curious that he would be snooping around Elizabeth's office prior to her untimely demise.", 7, 3, &dialog_3_19);
inline extern Dialog dialog_3_17 = create_npc_dialog("I must admit, Vincent, I find it intriguing that you express suspicion towards Marcus Hawthorne. Care to elaborate on that?", 0, 3, &dialog_3_18);
inline extern Dialog dialog_3_16 = create_npc_dialog("I understand your perspective, detective. But I assure you, Olivia and I are innocent. We had nothing to do with this heinous act. We were simply going about our duties when we received the shocking news. Marcus on the other hand is a man that cannot be trusted.", 7, 3, &dialog_3_17);
inline extern Dialog dialog_3_15 = create_npc_dialog("Yes, the bond between you and Olivia is quite evident. You both share a deep connection, working alongside Elizabeth day in and day out. It would seem unlikely that either of you would have a hand in her demise. However, in my line of work, I can't afford to overlook any possibilities.", 0, 3, &dialog_3_16);
inline extern Dialog dialog_3_14 = create_npc_dialog("Tragedy doesn't even begin to describe it, detective. Elizabeth's death has left me utterly stunned, shaken to my very core. We had a bond, you know. A bond forged through trust and loyalty. I can't believe someone would dare to harm her.", 7, 3, &dialog_3_15);
inline extern Dialog dialog_3_13 = create_npc_dialog("Vincent, it's quite a scene we have here. Elizabeth, the one you were so close to, meeting such an unfortunate end. A true tragedy indeed.", 0, 3, &dialog_3_14);
inline extern Dialog dialog_3_12 = create_npc_dialog("The mansion's somber embrace seemed to hold its breath as Conan ventured deeper into its murky depths. Every step echoed with a tinge of apprehension, for he knew that behind the next door, another enigma awaited. And there, in a dimly lit office, sat Vincent Delacroix, a man of secrets and deceit. A mere glance exchanged between them carried the weight of a thousand unspoken truths, setting the stage for a perilous exchange of words that would determine the fate of this twisted tale.", 1, 3, &dialog_3_13);
inline extern Dialog dialog_3_11 = create_npc_dialog("(straightening his fedora, determination etched on his face) The shadows are my playground, Olivia. And the truth... it shall be revealed, one clue at a time.", 0, 3, &dialog_3_12);
inline extern Dialog dialog_3_10 = create_npc_dialog("(leaning closer, a glimmer of hope in her eyes) Find that truth, Detective. Bring justice to Elizabeth's memory. But tread carefully, for the shadows hold their secrets close, and danger lurks in the alleys of the unknown.", 6, 3, &dialog_3_11);
inline extern Dialog dialog_3_9 = create_npc_dialog("(smirking) Indeed, trust is a fragile currency in these labyrinthine corridors of suspicion. But fear not, Miss Montgomery. I have a knack for unraveling the tangled threads of deceit. And with your guidance, we shall uncover the truth that lurks beneath the surface.", 0, 3, &dialog_3_10);
inline extern Dialog dialog_3_8 = create_npc_dialog("(pausing, her voice tinged with caution) Ah, Amelia. Sisters, bound by blood and secrets. There's always been an undercurrent of tension, a dance of hidden conflicts between them. Yet, it's hard to imagine her capable of such darkness. Still, in this noir tale, trust becomes a fleeting luxury.", 6, 3, &dialog_3_9);
inline extern Dialog dialog_3_7 = create_npc_dialog("(leaning back, his eyes glinting with intrigue) Loyalty can be a double-edged blade, Olivia. And what about Amelia Summers? Elizabeth's sister. Any unease there?", 0, 3, &dialog_3_8);
inline extern Dialog dialog_3_6 = create_npc_dialog("(meeting his gaze, her tone filled with conviction) Access, yes. But involvement? Never. I may have known Elizabeth's innermost workings, but I swear on the shadowed alleys of this city, I had no hand in her demise. (Her eyes flickered with a mix of frustration and concern.) I know these suspects well, Detective. They're like family. Marcus Hawthorne, though... there's something amiss about him. His actions have raised my suspicions, and my loyalty to the others fuels my doubts.", 6, 3, &dialog_3_7);
inline extern Dialog dialog_3_5 = create_npc_dialog("(leaning in, his voice low and intense) You've had an intimate view into her world, Olivia. Her routines, her secrets. Some might say you had unparalleled access.", 0, 3, &dialog_3_6);
inline extern Dialog dialog_3_4 = create_npc_dialog("(nodding, her expression grave) Caught up indeed. The winds of tragedy blew through these halls, and we found ourselves in its merciless grip. (She paused, her eyes narrowing.) Elizabeth... she was more than just an employer to me. We were confidantes, allies. I find it unfathomable that someone close to her would be capable of such a heinous act.", 6, 3, &dialog_3_5);
inline extern Dialog dialog_3_3 = create_npc_dialog("(smirking) Secrets have a way of surfacing, even in the darkest corners. I hear you and Mr. Delacroix were caught up in the storm tonight.", 0, 3, &dialog_3_4);
inline extern Dialog dialog_3_2 = create_npc_dialog("(with a hint of weariness in her voice) Longer than I anticipated, Mr. Detective. The night took an unexpected turn, and here we are, surrounded by secrets and shadows.", 6, 3, &dialog_3_3);
inline extern Dialog dialog_3_1 = create_npc_dialog("(leaning against the door frame, his trench coat draped over his shoulders) Long night, Miss Montgomery?", 0, 3, &dialog_3_2);
inline extern Dialog stage_4_root = create_npc_dialog("The dimly lit office was cloaked in an air of mystery as Conan entered, his sharp gaze fixed on Olivia Montgomery, Elizabeth's enigmatic personal assistant. Olivia, her eyes darting between the stacks of papers on her desk, looked up with a mix of surprise and curiosity as Conan approached.", 1, 3, &dialog_3_1);

#endif // STAGE_3_H